import Nav from "$/components/Nav";
import Provider from "$/components/provider";
import { authOptions } from "$/lib/auth";
import { getServerSession } from "next-auth";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className="">
        <Provider session={session}>
          <Nav />
          {children}
        </Provider>
      </body>
    </html>
  );
}
